# Generated by Django 4.2.3 on 2023-10-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Magazine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="magazines_images")),
                ("title_english", models.CharField(max_length=255)),
                ("title_french", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("link", models.URLField()),
            ],
        ),
    ]
