# Generated by Django 4.2.3 on 2023-10-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_magazine"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecard",
            name="pdf",
            field=models.FileField(default="default.pdf", upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="magazine",
            name="pdf",
            field=models.FileField(default="default.pdf", upload_to="documents/"),
        ),
    ]
