# Generated by Django 4.2.3 on 2023-10-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_articlecard_pdf_magazine_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlecard",
            old_name="pdf",
            new_name="pdf_english",
        ),
        migrations.RenameField(
            model_name="magazine",
            old_name="pdf",
            new_name="pdf_english",
        ),
        migrations.AddField(
            model_name="articlecard",
            name="pdf_french",
            field=models.FileField(default="default.pdf", upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="magazine",
            name="pdf_french",
            field=models.FileField(default="default.pdf", upload_to="documents/"),
        ),
    ]
