# Generated by Django 4.2.3 on 2023-10-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_pdf_articlecard_pdf_english_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlecard",
            name="link",
        ),
        migrations.RemoveField(
            model_name="magazine",
            name="link",
        ),
    ]
